### PR TITLE
web pages html css

### PR DESCRIPTION
**Pull request by JokoArdh**
website html and css

### CODE REVIEW

**Comment by JokoArdh** [comment]
website html and css bigenner

**Comment by Naman-sharma00100** [comment]
Hello there, I see you have translated the website, It wont be visible much inside the folder so I have created a new branch for whole translated website. Pls resend the PR on the new branch. Thank you.

**Comment by Naman-sharma00100** [comment]
@JokoArdh Pls send the PR for this branch: "Translated_main".

**Comment by JokoArdh** [comment]
sorry can i replay fork

**Pull request closed without merging**
